package com.chanu;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import com.chanu.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return123 'true'", classUnderTest.someLibraryMethod());
    }
}
